export const BOOK_TYPES = {
  GETALLBOOK:"BOOK/GETALL",
  INFOBOOK:"BOOK/INFO",
  ARRCART:"BOOK/ARRCART",
  CHANGESTATUSARRCART:"BOOK/CHANGESTATUSARRCART"
  
}

export const ERROR = {
  NOT_EXIST: 'ERROR/NOT_EXIST',
  DUPLICATE: 'ERROR/DUPLICATE',
}

