export const AUTH_TYPES = {
  AUTH: {
    REGISTER: 'AUTH/REGISTER',
    LOGIN: 'AUTH/LOGIN',
    LOGOUT: 'AUTH/LOGOUT',
    VERIFY: 'AUTH/VERIFY',
    INFO: 'AUTH/GET_INFO', 
    HISTORY:'AUTH/HISTORY',
    V:'AUTH/V',
    CHANGEV:'AUTH/CHANGEV'
  },
  DELETE: 'USER/DELETE',
  GET: 'USER/GET_INFO',
  UPDATE: 'USER/UPDATE',
  GETKEY:'USER/GETKEY'
}

export const ERROR = {
  NOT_EXIST: 'ERROR/NOT_EXIST',
  DUPLICATE: 'ERROR/DUPLICATE',
}

export const EVENT = {
  RUNNING: 'RUNNING',
  RESULT: 'RESET_RESULT'
}