const GAME_TYPES = {
  ROOM: {
    FIND: "ROOM/FIND",
    FOUND: "ROOM/FOUND",
    CREATE: "ROOM/CREATE",
    START: "ROOM/START_GAME",
    NEW_PLAYER: "ROOM/NEW_PLAYER",
    LEAVE: "ROOM/LEAVE",
    END: "ROOM/END_GAME",
    TITLE: "ROOM/TITLE",
  },
  PLAYER: {
    SET_USERNAME: "PLAYER/SET_USERNAME",
    ROLE: "PLAYER/ROLE",
    VOTE: "PLAYER/VOTE",
    USE_SKILL: "PLAYER/USE_SKILL",
    DEAD: "PLAYER/DEAD",
    CHAT: "PLAYER/CHAT",
  },
  EVENT: {
    SHIFT: {
      CHANGE: 'SHIFT/CHANGE',
      DAY: 'SHIFT/DAY',
      NIGHT: 'SHIFT/NIGHT'
    },
    VOTE_KILL: "EVENT/VOTE_KILL",
    WOLF_VOTE: "EVENT/VOTE_WOLF",
    FREE_TIME: "EVENT/FREE_TIME",
    WAKE_UP: "EVENT/WAKE_UP",
    DEBATE: "EVENT/DEBATE"
  },
  STATUS: {
    SUCCESS: "SUCCESS",
    FAIL: "FAIL"
  },
  ERROR: {
    NOT_EXIST: "NOT_EXIST"
  }
}
export default GAME_TYPES